### ISSUE TITLE
Intellij에서 log 색상이 정상적으로 적용되지 않는 이슈

### ISSUE THREAD

**Issue by youngchaena** [schooldevops/kotlin-springboot-study-with-kido#1]
## 이슈
intellij에서 log 색상이 정상적으로 출력되지 않는 이슈
![스크린샷 2023-10-31 오전 8 44 10](https://github.com/schooldevops/kotlin-springboot-study-with-kido/assets/2259291/3731b226-cdce-4d85-be96-a105cbcc7bb3)

## 해결
spring.output.ansi.enabled = always로 설정해주면 색상 적용됨
```yaml
spring:
  ...
  output:
    ansi:
      enabled: always
```
![스크린샷 2023-10-31 오전 8 47 10](https://github.com/schooldevops/kotlin-springboot-study-with-kido/assets/2259291/63eb032d-4c56-4f79-8415-5bd65b17b76a)
